### ISSUE TITLE
Location from config is returned as string instead of object

### ISSUE THREAD

**Issue by skrollme** [tronbyt/server#579]
Hello
I already checked the old/closed issues and found some concerning changes in the "location" object but I think this is somewhat different:        

My app's code looks like this and worked well before the latest update of tronbyt server.
```
location = config.get("location", DEFAULT_LOCATION)
lng = str(location["lng"])
```

But after the update I get a string instead of object which - when printed - looks like this:
```
map[description:CITYNAME, NI, Germany lat:XX.XXXXXX lng:YY.YYYYYY locality: CITYNAME place_id:ZZZZZZZZZZZZZZZZZZZZZZZZ timezone:Europe/Berlin]
```

I am no pro in Python or Starlark so I'm not sure if I'm doing something wrong or it has something to do with the server

**Comment by IngmarStein** [comment]
Thank you for the report! This should be fixed with #580. Please update and re-test your app.

**Comment by skrollme** [comment]
Awesome and thank you for your response :D I will check the update and report back

**Comment by skrollme** [comment]
Hello @IngmarStein 
I just pulled the latest docker images (currently on revision #fb0515bdc10039a3241a891a0e55514005b126bb) but the problem is still present. The code from my initial post still fails due to `location` being a string

**Comment by IngmarStein** [comment]
Besides pulling the image, did you also recreate the container?

**Comment by skrollme** [comment]
yep. I ran `docker compose pull && docker compose down && docker compose up -d`. And - just to be sure - I did it once again. Also re-added the app to my Tronbyt and reconfigured it (e.g. setting a new location)

**Comment by IngmarStein** [comment]
Just to double-check: what version is shown on the user page at the bottom?

**Comment by skrollme** [comment]
There was another new image to pull this morning, which I did. The version info says `Server main-e5d406a`

**Comment by IngmarStein** [comment]
@skrollme would you be able to share some reproduction steps? I was able to reproduce this previously, but not with the latest version. Which app is it that you're trying?

**Comment by skrollme** [comment]
I used the chance to wipe and restart my setup with the latest docker image and now it works 🤷‍♂️ I'm sorry that I kept this open here but thank you very much for your support, @IngmarStein  🫶

**Comment by IngmarStein** [comment]
Glad to hear that it's resolved! That might point to some bad data from the previous version stuck in an app config. Cheers and have fun with Tronbyt :)
